# Generated by Django 5.2.6 on 2025-09-16 11:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('essentials', 'Football Essentials'), ('apparel', 'Apparel & Jerseys'), ('accessories', 'Accessories'), ('collectibles', 'Lifestyle & Collectibles'), ('training', 'Training & Fitness')], max_length=50)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
