# Generated by Django 5.2.6 on 2025-10-01 01:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 10, 1, 1, 34, 47, 483566, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
